name: "Pull Request Labeler"
on:
  pull_request:
    branches: [main]
jobs:
  Label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
